### ISSUE TITLE
(Question) Is it possible to make a bootable USB?

### ISSUE THREAD

**Issue by moliata** [ivandavidov/minimal-linux-script#13]
Hello,
Sorry if this is a stupid question. This is my first time looking at building Linux at all. As far as I read about `syslinux` bootloader, it seems that it's possible to make a bootable USB with the help of `dd`. Can you clarify whether that works, if you have tested that. Currently my goal is to build the most minimal Linux kernel based OS that could run from a bootable USB for learning purposes.
Best regards,
Ben.

**Comment by ivandavidov** [comment]
Although you already closed the question, I suggest you experiment with ``syslinux`` and/or ``extlinux`` and use the artifacts, produced by the MLS build process, i.e. the ``kernel`` binary and the ``initramfs`` archive. In addition, you can create your own "virtual" hard drive with ``truncate``, loop-mount it locally and then try to install your OS there. After that attach the finalized image file to a virtual machine and continue experimenting. In this way you don't need to reflash your USB device. You only do that when everything works fine on the "virtual" hard drive.
