### ISSUE TITLE
(Question) Regarding linuxrc

### ISSUE THREAD

**Issue by moliata** [ivandavidov/minimal-linux-script#14]
Hello,
What is `linuxrc`, why do you delete it and is it possible to build the MLS without removing it?
Best regards,
Ben.

**Comment by ivandavidov** [comment]
I'm sure you can find the answer by using Google or any other search engine. Nevertheless, this is the short answer is that ``linuxrc`` is the first thing that the kernel executes when the OS is started in the old-fashioned ``initrd`` boot scheme. Nowadays all Linux based operating systems use ``initramfs`` boot scheme where the first thing that the kernel executes is ``/init``.

MLS uses ``initramfs`` boot scheme, therefore the file ``linuxrc`` is not used, therefore it can be safely removed.
