### ISSUE TITLE
Compile kernel and rootfs in xz format

### ISSUE THREAD

**Issue by sommoMicc** [ivandavidov/minimal-linux-script#15]
Hi, I'm trying to create a bootable usb using your systemd-boot configuration. The problem is that it requires the kernel and rootfs to be in xz format and not in gz, while this script compiles them in xz. How can I edit the script to obtain "kernel.xz" and "rootfs.xz" instead of gz format?

**Comment by ivandavidov** [comment]
Could you please elaborate on the issue? I'm not sure I understand what the
problem is.

**Comment by sommoMicc** [comment]
Basically I need to create a USB stick with the compiled minimal linux. However, kernel and rootfs are in .gz format. When I create the USB stick with "systemd-boot"  and try to boot from the USB I obtain "kernel.gz: Invalid format" error message, so I think that I've to compile kernel and rootfs in xz format instead of gz, but I don't know how

**Comment by ivandavidov** [comment]
Please be aware that the Minimal Linux Script kernel is compiled with default options and the EFI stub is not included. You should recompile your kernel and include EFI stub, then try again. Refer to one of the many online tutorials which describe how to use the kernel's ``make menuconfig``, then add the EFI stub option and compile the kernel.

**Comment by ivandavidov** [comment]
Another simple change is to update the ``systemd-boot`` configuration from ``xz`` to ``gz`` with whatever editor you want. Once you add the EFI stub and you update the boot configuration, there will be no need to recompile the kernel and compress it with ``xz``.
