### ISSUE TITLE
[QUESTION] how to boot on Raspberry Pi?

### ISSUE THREAD

**Issue by MESWEB** [ivandavidov/minimal-linux-script#16]
How I can boot this OS with Raspberry Pi 1 / 32 bit ARM CPU? Using SD Card Reader built in?

**Comment by ivandavidov** [comment]
You should get familiar with the Raspberry Pi boot specification and build MLS in a way that the Pi bootloader runs your kernel and your initramfs. Currently, there is no roadmap to support Raspberry Pi devices.
