### ISSUE TITLE
[QUESTION] Installing apps

### ISSUE THREAD

**Issue by MESWEB** [ivandavidov/minimal-linux-script#17]
How I can install more apps? I want mount USB and SD Card Reader. I wish get there mysql, openssl, samba and more what I need. What about browsers?

**Comment by ivandavidov** [comment]
MLS doesn't provide a mechanism that allows you to add more apps. If you want additional apps in MLS, you should add them manually to the initramfs. This means that all your apps will be in the RAM. Also, it's entirely up to you to add these apps, including their shared libraries and other dependencies.

Perhaps you should try Slax or Ubuntu Mini.
